### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by SprintSerwis**

### CODE REVIEW

**Comment by redaxmedia** [comment]
Please let us solve the issue, I have it on my list. Your refactoring changed the way it is working. EN should always be loaded and merged with the current language, so we have fallback values for those who are missing in the current language.

**Comment by SprintSerwis** [comment]
I think the common elements of all languages should not be copied in every language file, so I created a separate file all.json

**Comment by redaxmedia** [comment]
I understand this but the common things of all languages files is the en.json because it is the base that is going to be merged by the architecture purpose.

**Comment by SprintSerwis** [comment]
OK, I understand.

**Pull request closed without merging**
