### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by SprintSerwis**

### CODE REVIEW

**Comment by redaxmedia** [comment]
Hello,

thanks for contributing - what are you trying to fix here?

The idea of the init Method is to load the EN translations and merge it with the translation that was detected. If for example PL translation is missing a key, the EN key is present.

To sum it up: it was written to work the way it is at the moment. The EN translation btw. contains extra fields, so a merge is needed for a second reason: https://github.com/redaxmedia/redaxscript/blob/master/languages/en.json#L2-L42

**Comment by SprintSerwis** [comment]
For now I am studying his script, and learn to use github.
Also, I test your script locally and on the web server.
Sorry I do not have much time, but your script is good, so I try to help as much as possible.
Thanks for the additional information.

**Comment by redaxmedia** [comment]
Hello,


did you use Redaxscript 2.x.x too or just Redaxscript 3.0.0? What are 
you coding skills? PHP, JS, CSS? :D


Best regards

Henry


Am 30.10.2016 um 21:36 schrieb Sławomir Załęcki:

**Comment by SprintSerwis** [comment]
I tested a little bit 2.6.2, but I'd rather use 3.0.0 on the website.
I have a general idea of programming in PHP. I improved and modified the other scripts CMS. I know HTML and CMS. JavaScript poorly, but I'm learning.
Unfortunately I know English language on average, so bit I have to use google translator.

**Comment by redaxmedia** [comment]
It would be great to have a little chat, let's meet on Gitter. What do you think? Send me a time.

**Pull request closed without merging**
